sensor_msgs/Image normalisedImage
std_msgs/UInt32 imageIndex
std_msgs/UInt32 searchRange # total images searched = 1 + 2*searchRange
---
std_msgs/Int32MultiArray offsets
std_msgs/Float32MultiArray correlations